from fastapi import APIRouter

from app.models.modules import (
    ActionItem,
    CommitteeMember,
    CommitteeSession,
    Consent,
    Dpo,
    Finding,
    ImplementationProject,
    Policy,
    Procedure,
    Risk,
    Ticket,
    TreatmentActivity,
)
from app.routers.crud_factory import create_crud_router
from app.schemas.modules import (
    ActionCreate,
    ActionRead,
    ActionUpdate,
    CommitteeMemberCreate,
    CommitteeMemberRead,
    CommitteeMemberUpdate,
    CommitteeSessionCreate,
    CommitteeSessionRead,
    CommitteeSessionUpdate,
    ConsentCreate,
    ConsentRead,
    ConsentUpdate,
    DpoCreate,
    DpoRead,
    DpoUpdate,
    FindingCreate,
    FindingRead,
    FindingUpdate,
    PolicyCreate,
    PolicyRead,
    PolicyUpdate,
    ProcedureCreate,
    ProcedureRead,
    ProcedureUpdate,
    ProjectCreate,
    ProjectRead,
    ProjectUpdate,
    RiskCreate,
    RiskRead,
    RiskUpdate,
    TicketCreate,
    TicketRead,
    TicketUpdate,
    TreatmentActivityCreate,
    TreatmentActivityRead,
    TreatmentActivityUpdate,
)

router = APIRouter()

routers = [
    create_crud_router(model=Dpo, create_schema=DpoCreate, update_schema=DpoUpdate, read_schema=DpoRead, prefix="/dpos", tag="DPO"),
    create_crud_router(
        model=ImplementationProject,
        create_schema=ProjectCreate,
        update_schema=ProjectUpdate,
        read_schema=ProjectRead,
        prefix="/projects",
        tag="Proyecto de implementacion",
    ),
    create_crud_router(
        model=TreatmentActivity,
        create_schema=TreatmentActivityCreate,
        update_schema=TreatmentActivityUpdate,
        read_schema=TreatmentActivityRead,
        prefix="/treatment-activities",
        tag="Actividades de tratamiento",
    ),
    create_crud_router(
        model=CommitteeMember,
        create_schema=CommitteeMemberCreate,
        update_schema=CommitteeMemberUpdate,
        read_schema=CommitteeMemberRead,
        prefix="/committee-members",
        tag="Comite Ejecutivo - miembros",
    ),
    create_crud_router(
        model=CommitteeSession,
        create_schema=CommitteeSessionCreate,
        update_schema=CommitteeSessionUpdate,
        read_schema=CommitteeSessionRead,
        prefix="/committee-sessions",
        tag="Comite Ejecutivo - sesiones",
    ),
    create_crud_router(model=Finding, create_schema=FindingCreate, update_schema=FindingUpdate, read_schema=FindingRead, prefix="/findings", tag="Hallazgos"),
    create_crud_router(model=Risk, create_schema=RiskCreate, update_schema=RiskUpdate, read_schema=RiskRead, prefix="/risks", tag="Riesgos"),
    create_crud_router(model=ActionItem, create_schema=ActionCreate, update_schema=ActionUpdate, read_schema=ActionRead, prefix="/actions", tag="Acciones"),
    create_crud_router(
        model=Procedure,
        create_schema=ProcedureCreate,
        update_schema=ProcedureUpdate,
        read_schema=ProcedureRead,
        prefix="/procedures",
        tag="Procedimientos",
    ),
    create_crud_router(model=Ticket, create_schema=TicketCreate, update_schema=TicketUpdate, read_schema=TicketRead, prefix="/tickets", tag="Tickets"),
    create_crud_router(model=Consent, create_schema=ConsentCreate, update_schema=ConsentUpdate, read_schema=ConsentRead, prefix="/consents", tag="Consentimientos"),
    create_crud_router(model=Policy, create_schema=PolicyCreate, update_schema=PolicyUpdate, read_schema=PolicyRead, prefix="/policies", tag="Politica de tratamiento"),
]

for module_router in routers:
    router.include_router(module_router)
